name: Deploy Lambda and API Gateway for LINE bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          npm install

      - name: Install necessary packages
        run: |
          sudo apt-get update
          sudo apt install musl-tools

      - name: Deploy using CDK
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: |
          cdk bootstrap
          cdk deploy apigateway-line-bot-stack --require-approval never